In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
np.random.seed(45)
titanic_data = pd.read_csv('data.csv')

In [2]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# Dropping Irrelevant columns
titanic_data = titanic_data.drop(['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked'], axis=1)

In [4]:
titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)
titanic_data['Fare'].fillna(titanic_data['Fare'].median(), inplace=True)
#Replacing null values with median

In [5]:
titanic_data['Sex'] = titanic_data['Sex'].map({'male': 0, 'female': 1})# marking male as 0 and female as 1

In [6]:
# Split features and target
X = titanic_data.drop('Survived', axis=1)
y = titanic_data['Survived'].values.reshape(-1, 1)

In [7]:
X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare
0       3    0  22.0      1      0   7.2500
1       1    1  38.0      1      0  71.2833
2       3    1  26.0      0      0   7.9250
3       1    1  35.0      1      0  53.1000
4       3    0  35.0      0      0   8.0500

In [8]:
# Normalizing features
scaler = StandardScaler() 
X = scaler.fit_transform(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

In [10]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.01):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate

        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.bias_hidden = np.zeros((1, self.hidden_size))
        self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size)
        self.bias_output = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.hidden_layer_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        self.hidden_layer_output = self.sigmoid(self.hidden_layer_input)

        self.output_layer_input = np.dot(self.hidden_layer_output, self.weights_hidden_output) + self.bias_output
        self.predicted_output = self.sigmoid(self.output_layer_input)

        return self.predicted_output

    def backward(self, X, y, output):
        error = y - output
        d_output = error * self.sigmoid_derivative(output)

        error_hidden_layer = d_output.dot(self.weights_hidden_output.T)
        d_hidden_layer = error_hidden_layer * self.sigmoid_derivative(self.hidden_layer_output)

        self.weights_hidden_output += self.hidden_layer_output.T.dot(d_output) * self.learning_rate
        self.bias_output += np.sum(d_output, axis=0,) * self.learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden_layer) * self.learning_rate
        self.bias_hidden += np.sum(d_hidden_layer, axis=0) * self.learning_rate

    def mean_squared_error(self, y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)

    def train(self, X, y, epochs):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)
            loss = self.mean_squared_error(y, output)
            print(f"Epoch {epoch + 1} - Loss: {loss}")

    def predict(self, X):
        return self.forward(X)

In [11]:
input_size = X_train.shape[1]
hidden_size = 4
output_size = 1
nn = NeuralNetwork(input_size, hidden_size, output_size)

In [12]:
num_epochs = 100
nn.train(X_train, y_train, num_epochs)

Epoch 1 - Loss: 0.26199953057084985
Epoch 2 - Loss: 0.2564608706600279
Epoch 3 - Loss: 0.2517769815075819
Epoch 4 - Loss: 0.24760167469138836
Epoch 5 - Loss: 0.24383937608108514
Epoch 6 - Loss: 0.24042267732879422
Epoch 7 - Loss: 0.23728907529272292
Epoch 8 - Loss: 0.23438126268294063
Epoch 9 - Loss: 0.23164800595169494
Epoch 10 - Loss: 0.22904420418771068
Epoch 11 - Loss: 0.22653081222063365
Epoch 12 - Loss: 0.2240748567657899
Epoch 13 - Loss: 0.22164945284470255
Epoch 14 - Loss: 0.21923370992637434
Epoch 15 - Loss: 0.21681249859689858
Epoch 16 - Loss: 0.21437610078170638
Epoch 17 - Loss: 0.2119197752174199
Epoch 18 - Loss: 0.20944326049638337
Epoch 19 - Loss: 0.20695022932115487
Epoch 20 - Loss: 0.20444770457344388
Epoch 21 - Loss: 0.20194544788049468
Epoch 22 - Loss: 0.1994553302564326
Epoch 23 - Loss: 0.1969906895631673
Epoch 24 - Loss: 0.19456567235363914
Epoch 25 - Loss: 0.19219455400899263
Epoch 26 - Loss: 0.18989103906997123
Epoch 27 - Loss: 0.1876675678548477
Epoch 28 - Loss: 0.1855346895225412
Epoch 29 - Loss: 0.18350058590840995
Epoch 30 - Loss: 0.18157082186307433
Epoch 31 - Loss: 0.17974835110916962
Epoch 32 - Loss: 0.17803374418442905
Epoch 33 - Loss: 0.17642556059788497
Epoch 34 - Loss: 0.17492077857712687
Epoch 35 - Loss: 0.17351521532415873
Epoch 36 - Loss: 0.17220389948570272
Epoch 37 - Loss: 0.17098138120238202
Epoch 38 - Loss: 0.16984197916301608
Epoch 39 - Loss: 0.16877997045504609
Epoch 40 - Loss: 0.16778973108492187
Epoch 41 - Loss: 0.1668658353019844
Epoch 42 - Loss: 0.1660031214707192
Epoch 43 - Loss: 0.16519673158964174
Epoch 44 - Loss: 0.16444213074566574
Epoch 45 - Loss: 0.1637351118690395
Epoch 46 - Loss: 0.16307179018406223
Epoch 47 - Loss: 0.16244859081219293
Epoch 48 - Loss: 0.16186223214045176
Epoch 49 - Loss: 0.1613097068568862
Epoch 50 - Loss: 0.1607882619880829
Epoch 51 - Loss: 0.16029537884364897
Epoch 52 - Loss: 0.15982875346058273
Epoch 53 - Loss: 0.15938627792377288
Epoch 54 - Loss: 0.15896602279546262
Epoch 55 - Loss: 0.15856622079760235
Epoch 56 - Loss: 0.15818525184188406
Epoch 57 - Loss: 0.1578216294820227
Epoch 58 - Loss: 0.15747398886353303
Epoch 59 - Loss: 0.15714107626137414
Epoch 60 - Loss: 0.15682174031873158
Epoch 61 - Loss: 0.15651492512193138
Epoch 62 - Loss: 0.1562196652533787
Epoch 63 - Loss: 0.1559350829358018
Epoch 64 - Loss: 0.15566038728812623
Epoch 65 - Loss: 0.15539487552153267
Epoch 66 - Loss: 0.15513793558355082
Epoch 67 - Loss: 0.15488904930403366
Epoch 68 - Loss: 0.15464779456419417
Epoch 69 - Loss: 0.15441384454654267
Epoch 70 - Loss: 0.15418696197759008
Epoch 71 - Loss: 0.15396698673173698
Epoch 72 - Loss: 0.15375381638997299
Epoch 73 - Loss: 0.15354738118806185
Epoch 74 - Loss: 0.1533476166786605
Epoch 75 - Loss: 0.15315443856142597
Epoch 76 - Loss: 0.15296772388925417
Epoch 77 - Loss: 0.15278730123939585
Epoch 78 - Loss: 0.1526129501198843
Epoch 79 - Loss: 0.15244440781439683
Epoch 80 - Loss: 0.15228138073542116
Epoch 81 - Loss: 0.15212355728758106
Epoch 82 - Loss: 0.1519706199200008
Epoch 83 - Loss: 0.15182225499906615
Epoch 84 - Loss: 0.15167815999426024
Epoch 85 - Loss: 0.15153804806720364
Epoch 86 - Loss: 0.15140165047350662
Epoch 87 - Loss: 0.15126871729507127
Epoch 88 - Loss: 0.15113901700065424
Epoch 89 - Loss: 0.1510123352527648
Epoch 90 - Loss: 0.15088847328300667
Epoch 91 - Loss: 0.15076724606868344
Epoch 92 - Loss: 0.1506484804699403
Epoch 93 - Loss: 0.1505320134303053
Epoch 94 - Loss: 0.15041769030216373
Epoch 95 - Loss: 0.15030536332933173
Epoch 96 - Loss: 0.15019489029850763
Epoch 97 - Loss: 0.15008613335753213
Epoch 98 - Loss: 0.1499789579892821
Epoch 99 - Loss: 0.14987323212440148
Epoch 100 - Loss: 0.1497688253730947

In [13]:
predictions = np.round(nn.predict(X_test))
accuracy = np.mean(predictions == y_test)
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.8059701492537313

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix,mean_squared_error

predicted = predictions.flatten()

accuracy = accuracy_score(y_test, predicted)
precision = precision_score(y_test, predicted)
recall = recall_score(y_test, predicted)
f1 = f1_score(y_test, predicted)
conf_matrix = confusion_matrix(y_test, predicted)
mse = mean_squared_error(y_test,predicted)

In [15]:
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"MSE: {mse:.4f}")

Accuracy: 0.8060
Precision: 0.7810
Recall: 0.7387
F1 Score: 0.7593
MSE: 0.1940

In [16]:
print(f"Confusion Matrix {conf_matrix}")

Confusion Matrix [[134  23]
 [ 29  82]]